# Default values for fluent-gcp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: gcr.io/stackdriver-agents/stackdriver-logging-agent
  tag: 0.3-1.5.34-1-k8s-1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

livenessProbe:
  initialDelaySeconds: 600
  periodSeconds: 60

# https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/156#issuecomment-442905956
customAuth:
  enabled: false

  #base64 encoded servoce account key
  json: ""

  projectID: ""
  vmID: ""
  zone: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector:
  beta.kubernetes.io/fluentd-ds-ready: "true"

tolerations:
  - key: "node.alpha.kubernetes.io/ismaster"
    effect: "NoSchedule"

affinity: {}
