{{- if (.Values.customAuth.enabled) }} 
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fluent-gcp.fullname" . }}-secret
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "fluent-gcp.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  application_default_credentials.json: |
{{ .Values.customAuth.json | nindent 4}}
{{- end }}

